Jmax/lg 8870 update vendor outage runbook
18F/identity-handbook pull request #441
Opened 2023-06-20 16:46 UTC by jmax-gsa

Updated section on Identity Verification outage flags.

2023-06-20 16:50 UTC, zachmargolis approved these changes
LGTM, I would also add @18F/identity-ada as reviewers too? Since that's the team with more context on these changes?

2023-06-22 21:06 UTC, benjaminchait requested changes

2023-06-22 21:06 UTC, benjaminchait commented on _articles/vendor-outage-response-process.md
> +  - Users will only be able to upload their IDs from their computer;
Minor nit: Users who _start_ on a mobile phone will be okay, but the _hybrid handoff_ will not be available.

What do you think of: "Users will need to add photos of their ID from the device on which they start; desktop users will not be presented the opportunity to switch to a mobile phone for adding their ID."

2023-06-22 21:06 UTC, benjaminchait commented on _articles/vendor-outage-response-process.md
> +  - Users will only be able to upload their IDs from their computer;
I don't think we use the Pinpoint "voice" feature for hybrid handoff, so I think this line could be removed? 

But all other content in this section makes sense!

2023-06-23 12:27 UTC, jmax-gsa commented on _articles/vendor-outage-response-process.md
> +  - Users will only be able to upload their IDs from their computer;
Re-worded your suggestion a bit; see if you like it.

2023-06-23 12:33 UTC, jmax-gsa commented on _articles/vendor-outage-response-process.md
> +  - Users will only be able to upload their IDs from their computer;
Nope. That's how the system behaves right now. I'm on board with changing it; I'll even write the ticket if you like. But right now, we don't offer hybrid handoff if voice is disabled.

The spec at `features/idv/outage_spec:185` check for exactly this behavior, and I just manually verified it to be extra doubleplus sure.

2023-06-23 14:45 UTC, benjaminchait commented on _articles/vendor-outage-response-process.md
> +  - Users will only be able to upload their IDs from their computer;
Ah, that is...surprising!

Yes, can you drop a ticket on Team Ada's board, and we can refine/update things accordingly?

2023-08-02 16:38 UTC, closed without merging