LG-11797 FlowPolicy documentation
18F/identity-handbook pull request #492
Opened 2023-12-14 17:13 UTC by soniaconnolly

Documentation for new FlowPolicy, which manages which steps are allowed for an Identity Verification session and user.

2023-12-14 19:43 UTC, solipet requested changes
A few suggestions (not required). The section on `idv_session` didn't get fleshed out - lets do that before merging.

2023-12-14 19:43 UTC, solipet commented on _articles/identity-verification-flow-policy.md
> +so it is only needed for controllers that use `:new` or `:index`.
can we highlight the fields?
```suggestion
* `key` - a unique key which is a symbol, for example `:agreement`
* `controller` - self, which is converted to the full controller "path" by `initialize`, for example
`/idv/agreement`
* `next_steps` - an array of keys of following steps once this step is submitted. Some controllers
only have one. Agreement has
several: `[:hybrid_handoff, :document_capture, :how_to_verify]`. If there is no following step, use
`FlowPolicy::FINAL`, for example PhoneErrorsController.step_info. It can be tricky to determine
where a step belongs. For example :request_letter is in the next_steps array for VerifyInfo
because even though it is accessed from the Phone step, the Phone step does not have to be
submitted to reach RequestLetter.
* `preconditions` - a proc with arguments `(idv_session:, user:)` that returns true if a
user is allowed to be on this step
* `undo_step` - a proc with arguments `(idv_session:, user:)` that clears any fields set by
this step. Called from `clear_future_steps!`
* `action` - a symbol for the controller action to use if jumping to this step. Defaults to `:show`,
so it is only needed for controllers that use `:new` or `:index`.
```

2023-12-14 19:43 UTC, solipet commented on _articles/identity-verification-flow-policy.md
> +`step_info.undo_step` for all future steps. It does not call `undo_step` for the current step,
Worth pointing out that `clear_future_steps!` works in reverse from the end.

```suggestion
`clear_future_steps!` looks at `step_info.next_steps` for the current step and calls
`step_info.undo_step` for all future steps, working from the last step back to the directly
adjacent next steps. It does not call `undo_step` for the current step,
```

2023-12-14 19:43 UTC, solipet commented on _articles/identity-verification-flow-policy.md
> +specs now have to have `idv_session` fully set up for the step under test. Use the `stub_step`
Since the example uses `stub_up_to` lets just mention that.

```suggestion
specs now have to have `idv_session` fully set up for the step under test. Use the `stub_up_to`
```

2023-12-14 19:43 UTC, solipet commented on _articles/identity-verification-flow-policy.md
> +invalidate step
Should we flesh this out?

2023-12-14 21:38 UTC, solipet approved these changes
Yay!

2023-12-14 21:38 UTC, theabrad approved these changes
Very nice write-up! LGTM

2023-12-15 16:41 UTC, matthinz approved these changes
Excellent work!

2023-12-15 17:30 UTC, merged