Update GPO designated receiver information
18F/identity-handbook pull request #497
Opened 2023-12-26 18:53 UTC by matthinz

- Ask folks to sign up directly or ask #login-team-ada for questions
- Describe how to update the PII in config

2023-12-26 18:56 UTC, matthinz commented
Preview is here: https://federalist-7d0b2b76-42fc-4df1-9825-8c3cd77e0a15.sites.pages.cloud.gov/preview/18f/identity-handbook/matthinz/11908-gpo-designated-receiver/articles/gpo-designated-receiver.html

2023-12-27 20:09 UTC, jmax-gsa requested changes
Can we emphasize the link to the spreadsheet a little? I missed it on first reading. Perhaps we could just repeat it in the 'What should I expect and how do I do it?' section.

2023-12-28 20:32 UTC, solipet approved these changes
LGTM!

2023-12-28 20:35 UTC, solipet commented
> Can we emphasize the link to the spreadsheet a little? I missed it on first reading. Perhaps we could just repeat it in the 'What should I expect and how do I do it?' section.

I might argue to rename that section simply "What should I expect" since the stuff at the bottom explains how. The spreadsheet is linked both in the "How and why?" section and in Matt's new content.

2023-12-29 18:05 UTC, zachmargolis commented on _articles/gpo-designated-receiver.md
> +Remember: **names and addresses are PII**. When reaching out to the new receiver, please request that they supply the information to you via an ephemeral channel (typically Google Chat or over a vide
I usually ask for a private Google Doc with the info that they should delete after

2023-12-29 19:37 UTC, matthinz commented on _articles/gpo-designated-receiver.md
> +Remember: **names and addresses are PII**. When reaching out to the new receiver, please request that they supply the information to you via an ephemeral channel (typically Google Chat or over a vide
Good point! Updated in d3fc407

2023-12-29 19:38 UTC, matthinz commented
> Can we emphasize the link to the spreadsheet a little? I missed it on first reading. Perhaps we could just repeat it in the 'What should I expect and how do I do it?' section.

As an inveterate skimmer, I agree with this and added a link to the "What should I expect..." section.

2024-01-02 17:13 UTC, jmax-gsa approved these changes
LGTM

2024-01-02 18:05 UTC, merged